#! /bin/sh

sxhkd &

picom &

bspc monitor -d 1 2

bspc config border_width        1
bspc config window_gap          32
bspc config bottom_padding	36 
bspc config right_padding	225
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
bspc rule -a Steam state=floating border=off follow=on 
bspc rule -a Surf state=tiled
bspc rule -a Lutris state=floating border=off follow=on 
bspc rule -a Emacs state=tiled 
