#! /bin/sh
#######################
## MINIBEAST BSPWMRC ##
#######################

# Startup
sxhkd &
picom &

# Monitor and desktop layout
bspc monitor -d  

# Padding and gaps
bspc config border_width        2
bspc config window_gap          11
bspc config bottom_padding	    36 
bspc config right_padding	    224
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Border and preselect colors
bspc config normal_border_color "333333"
bspc config active_border_color "333333"
bspc config focused_border_color "333333"
bspc config presel_feedback_color "1793d1"

## Use Pywal to generate border colors
## Source the colors.
#. "/home/jason/.cache/wal/colors.sh"

## Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"

# Window rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
bspc rule -a Steam state=floating border=off follow=on 
bspc rule -a Lutris state=floating border=off follow=on 
bspc rule -a android-studio state=floating border=off follow=on
bspc rule -a Sxiv state=floating follow=on
bspc rule -a dmenu state=floating border=off
bspc rule -a Kodi state=fullscreen
