#! /bin/sh

sxhkd &

picom &

bspc monitor -1

bspc config border_width        2
bspc config window_gap          32
bspc config bottom_padding	36 
bspc config right_padding	258
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
