#!/bin/zsh

for pkg in "$@"
do
    rm -rf /opt/sources/{packages,community}/$pkg
    echo "\033[1;34m:: \033[1;37mDownloading PKGBUILD...\033[0m"
    svn update /opt/sources/{packages,community}/$pkg >> /dev/null
    if [ -f "/opt/sources/packages/$pkg/trunk/PKGBUILD" ]; then
        cd /opt/sources/packages/$pkg/trunk/
    else
        cd /opt/sources/community/$pkg/trunk/
    fi
    if yes|makepkg -si; then
        echo "\033[1;34m:: \033[1;37mInstallation successful"
    else    
        echo "\033[1;34m:: \033[1;37mAdding key and retrying..."
        key="$(makepkg -i 2>&1 | grep FAILED | awk -F"key" '{print $2}')"
        gpg --recv-keys --keyserver hkps://hkps.pool.sks-keyservers.net:443 "${key: : -1}"
        if yes|makepkg -i; then
            echo "\033[1;34m:: \033[1;37mInstallation successful"
        else
            echo "\033[1;31mInstallation failed"
        fi
    fi
done
