#!/bin/zsh

for kern in "$@"
do
    rm -rfv /usr/src/*${kern}*
    rm -rfv /usr/lib/modules/*${kern}*
    rm -rfv /boot/*${kern}*
    rm -rfv /boot/efi/EFI/*${kern}*
    rm -rfv /boot/efi/EFI/Linux/*${kern}*
    rm -rfv /etc/mkinitcpio.d/*${kern}*
done
