#!/bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

# 01001101 01101001 01101110 01101001 01000010 01100101 01100001 01110011 01110100

# Startup programs
sxhkd &
picom &
polybar_launch &
nitrogen --restore &
dunst &

# Startup scripts
~/.config/bspwm/scripts/bspswallow &

# Monitor and desktop layout
bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8

# Padding and gaps
bspc config border_width        0
bspc config window_gap          12
bspc config top_padding	        22
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

# Etc
bspc config pointer_follows_monitor     true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config automatic_scheme            spiral
bspc config pointer_modifier            mod4

# Border and preselect colors
bspc config normal_border_color "333333"
bspc config active_border_color "333333"
bspc config focused_border_color "333333"
bspc config presel_feedback_color "1793d1"

## Use Pywal to generate border colors
## Source the colors.
#. "$XDG_CACHE_HOME/wal/colors.sh"

## Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"

# Window rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
bspc rule -a Steam state=floating border=off follow=on
bspc rule -a Lutris state=floating border=off follow=on
bspc rule -a android-studio state=floating border=off follow=on
bspc rule -a Sxiv state=floating follow=on
bspc rule -a Kodi state=fullscreen
